#!/usr/bin/env python3
"""
Generate a static Nav2 occupancy map from the official CAD drawing in
`docs/DASE7503 Group Project_QR Code and Gamefield.pdf` (Fig. "Simplified drawing of the Game Field").

输出:
  maps/gamefield_map.pgm   Nav2 OccupancyGrid (P5 灰度, 0=占用 255=空闲)
  maps/gamefield_map.yaml  配套 map_server YAML

坐标约定 (和 CAD 一致):
  世界 (0, 0, 0) = 场地**左下角**
  +x → 沿场地长边 (0 → 3020 mm)
  +y → 沿场地短边 (0 → 2000 mm)

用法:
  python3 scripts/generate_static_map.py
  # 或指定分辨率
  python3 scripts/generate_static_map.py --resolution 0.01
"""
import argparse
import os
import sys

try:
    import numpy as np
    from PIL import Image
except ImportError:
    print("需要 numpy + pillow: pip3 install --user numpy pillow", file=sys.stderr)
    sys.exit(1)


# ---- 课程 CAD 尺寸 (全部 mm) ----
FIELD_W_MM = 3020                     # 长边 (沿 +x)
FIELD_H_MM = 2000                     # 短边 (沿 +y)

# 左侧墙体突入的矩形 (从场地 x=0 向内伸)
LEFT_CUTOUT_W_MM = 800                # 向内宽度
LEFT_CUTOUT_H_MM = 1400               # 纵向高度
LEFT_CUTOUT_Y0_MM = 300               # 距场地底边的间距

# 右侧墙体突入的矩形 (从 x=FIELD_W 向内伸)
RIGHT_CUTOUT_W_MM = 600
RIGHT_CUTOUT_H_MM = 800
RIGHT_CUTOUT_Y0_MM = 600

BORDER_MM = 200                       # 图像外加一圈缓冲 (标记为 occupied), 防 Nav2 costmap 边界溢出


def generate(resolution_m: float, out_dir: str):
    def mm_to_px(mm: float) -> int:
        return int(round(mm / (resolution_m * 1000.0)))

    border_px = mm_to_px(BORDER_MM)
    field_w_px = mm_to_px(FIELD_W_MM)
    field_h_px = mm_to_px(FIELD_H_MM)
    total_w = field_w_px + 2 * border_px
    total_h = field_h_px + 2 * border_px

    # 默认整图 occupied (= 墙 / 场外)
    img = np.zeros((total_h, total_w), dtype=np.uint8)

    # 场地整体 free
    r0, c0 = border_px, border_px
    r1, c1 = border_px + field_h_px, border_px + field_w_px
    img[r0:r1, c0:c1] = 255

    # 图像 row=0 在顶 → 世界 y 需要翻转
    def world_to_img_rows(y0_mm: float, y1_mm: float):
        # world y 从底边起, image row 从顶起
        img_row0 = border_px + mm_to_px(FIELD_H_MM - y1_mm)  # 上边
        img_row1 = border_px + mm_to_px(FIELD_H_MM - y0_mm)  # 下边
        return img_row0, img_row1

    # 左侧墙体 (突入的矩形) — occupied
    lc_rows = world_to_img_rows(LEFT_CUTOUT_Y0_MM, LEFT_CUTOUT_Y0_MM + LEFT_CUTOUT_H_MM)
    img[lc_rows[0]:lc_rows[1], border_px:border_px + mm_to_px(LEFT_CUTOUT_W_MM)] = 0

    # 右侧墙体 — occupied
    rc_rows = world_to_img_rows(RIGHT_CUTOUT_Y0_MM, RIGHT_CUTOUT_Y0_MM + RIGHT_CUTOUT_H_MM)
    img[rc_rows[0]:rc_rows[1],
        border_px + mm_to_px(FIELD_W_MM - RIGHT_CUTOUT_W_MM):border_px + mm_to_px(FIELD_W_MM)] = 0

    os.makedirs(out_dir, exist_ok=True)
    pgm_path = os.path.join(out_dir, "gamefield_map.pgm")
    yaml_path = os.path.join(out_dir, "gamefield_map.yaml")

    # PIL 保存 PGM (P5 binary)
    Image.fromarray(img).save(pgm_path)

    # map.yaml
    # origin = 图像左下角像素在世界的坐标. 我们在场地外留了 BORDER mm 边缘, 所以世界 (0,0) 在图像内部
    origin_x_m = -BORDER_MM / 1000.0
    origin_y_m = -BORDER_MM / 1000.0

    yaml_content = (
        f"# CAD-derived static map for DASE7503 game field.\n"
        f"# Generated by scripts/generate_static_map.py; do NOT hand-edit.\n"
        f"image: gamefield_map.pgm\n"
        f"resolution: {resolution_m}\n"
        f"origin: [{origin_x_m}, {origin_y_m}, 0.0]\n"
        f"occupied_thresh: 0.65\n"
        f"free_thresh: 0.25\n"
        f"negate: 0\n"
    )
    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"Generated {pgm_path}  ({total_w}x{total_h} px @ {resolution_m} m/px)")
    print(f"Generated {yaml_path}")
    print(f"  field:   {FIELD_W_MM}x{FIELD_H_MM} mm = {field_w_px}x{field_h_px} px")
    print(f"  border:  {BORDER_MM} mm = {border_px} px")
    print(f"  origin:  ({origin_x_m}, {origin_y_m}) m = 图像左下角对应的世界坐标")
    print(f"  world:   (0,0) = 场地左下, +x → 长边 {FIELD_W_MM/1000}m, +y → 短边 {FIELD_H_MM/1000}m")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--resolution", type=float, default=0.02,
                   help="m/pixel, 默认 0.02 (2cm). 建图越细越费 costmap CPU.")
    p.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "maps"),
                   help="输出目录, 默认 <repo>/maps/")
    args = p.parse_args()
    generate(args.resolution, os.path.abspath(args.out))


if __name__ == "__main__":
    main()
