#!/usr/bin/env python3
"""
Generate a static Nav2 occupancy map from the official CAD drawing in
`docs/DASE7503 Group Project_QR Code and Gamefield.pdf` (Fig. "Simplified drawing of the Game Field").

输出:
  maps/gamefield_map.pgm   Nav2 OccupancyGrid (P5 灰度, 0=占用 255=空闲)
  maps/gamefield_map.yaml  配套 map_server YAML

坐标约定 (按 0420 CAD 直觉视图, x 横 y 纵):
  世界 (0, 0, 0) = 场地**左下角**
  +x → 沿场地短边 / 水平 (0 → 2000 mm)
  +y → 沿场地长边 / 垂直 (0 → 3020 mm)

用法:
  python3 scripts/generate_static_map.py
  # 或指定分辨率
  python3 scripts/generate_static_map.py --resolution 0.01
"""
import argparse
import os
import sys

try:
    import numpy as np
    from PIL import Image
except ImportError:
    print("需要 numpy + pillow: pip3 install --user numpy pillow", file=sys.stderr)
    sys.exit(1)


# ---- 课程 CAD 尺寸 (全部 mm), 以 0420 spec QR Code and Gamefield.pdf p.2 为准 ----
FIELD_W_MM = 2000                     # 短边 / 沿 +x (图像 width, 水平)
FIELD_H_MM = 3020                     # 长边 / 沿 +y (图像 height, 垂直)

# Rack 364×144 mm. LiDAR 13cm 高度看到 4 立柱反射. 必须画进 static map,
# 否则 AMCL likelihood field 没法 lock — LiDAR 看到 rack 但 map 是 free → 漂.
# 代价: nav planner 会绕开 rack, mission_fsm APPROACH_RACK 必须用 raw cmd_vel hack
# 钻进去 (跳过 Nav2 controller).
RACKS_MM = {
    "A": (530, 1890),
    "B": (1389, 1180),
    "C": (1693, 1688),
    "D": (378, 1081),
}
RACK_SIZE_X_MM = 364
RACK_SIZE_Y_MM = 144

# destination_zone (1400x800) + start_zone (600x800) 是地面 marked 区域 (绿/蓝垫),
# 不是物理墙, 机器人可以自由穿越 → 静态地图里不画.

BORDER_MM = 200                       # 图像外加一圈缓冲 (标记为 occupied), 防 Nav2 costmap 边界溢出


def generate(resolution_m: float, out_dir: str):
    def mm_to_px(mm: float) -> int:
        return int(round(mm / (resolution_m * 1000.0)))

    border_px = mm_to_px(BORDER_MM)
    field_w_px = mm_to_px(FIELD_W_MM)
    field_h_px = mm_to_px(FIELD_H_MM)
    total_w = field_w_px + 2 * border_px
    total_h = field_h_px + 2 * border_px

    # 默认整图 occupied (= 墙 / 场外)
    img = np.zeros((total_h, total_w), dtype=np.uint8)

    # 场地整体 free
    r0, c0 = border_px, border_px
    r1, c1 = border_px + field_h_px, border_px + field_w_px
    img[r0:r1, c0:c1] = 255

    # 图像 row=0 在顶 → 世界 y 需要翻转
    def world_to_img_rows(y0_mm: float, y1_mm: float):
        # world y 从底边起, image row 从顶起
        img_row0 = border_px + mm_to_px(FIELD_H_MM - y1_mm)  # 上边
        img_row1 = border_px + mm_to_px(FIELD_H_MM - y0_mm)  # 下边
        return img_row0, img_row1

    # 画 rack (occupied) — AMCL 需要它锁 LiDAR. nav planner 绕开 rack 是预期,
    # APPROACH_RACK 阶段 mission_fsm 走 raw cmd_vel 跳过 Nav2 钻进去.
    half_x = mm_to_px(RACK_SIZE_X_MM / 2)
    half_y = mm_to_px(RACK_SIZE_Y_MM / 2)
    for rack_id, (cx_mm, cy_mm) in RACKS_MM.items():
        cx_px = border_px + mm_to_px(cx_mm)
        # world y 朝上, image row 朝下 → 翻转
        cy_px_img = border_px + mm_to_px(FIELD_H_MM - cy_mm)
        r0 = max(0, cy_px_img - half_y)
        r1 = min(total_h, cy_px_img + half_y)
        c0 = max(0, cx_px - half_x)
        c1 = min(total_w, cx_px + half_x)
        img[r0:r1, c0:c1] = 0  # occupied

    os.makedirs(out_dir, exist_ok=True)
    pgm_path = os.path.join(out_dir, "gamefield_map.pgm")
    yaml_path = os.path.join(out_dir, "gamefield_map.yaml")

    # PIL 保存 PGM (P5 binary)
    Image.fromarray(img).save(pgm_path)

    # map.yaml
    # origin = 图像左下角像素在世界的坐标. 我们在场地外留了 BORDER mm 边缘, 所以世界 (0,0) 在图像内部
    origin_x_m = -BORDER_MM / 1000.0
    origin_y_m = -BORDER_MM / 1000.0

    yaml_content = (
        f"# CAD-derived static map for DASE7503 game field.\n"
        f"# Generated by scripts/generate_static_map.py; do NOT hand-edit.\n"
        f"image: gamefield_map.pgm\n"
        f"resolution: {resolution_m}\n"
        f"origin: [{origin_x_m}, {origin_y_m}, 0.0]\n"
        f"occupied_thresh: 0.65\n"
        f"free_thresh: 0.25\n"
        f"negate: 0\n"
    )
    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"Generated {pgm_path}  ({total_w}x{total_h} px @ {resolution_m} m/px)")
    print(f"Generated {yaml_path}")
    print(f"  field:   {FIELD_W_MM}x{FIELD_H_MM} mm = {field_w_px}x{field_h_px} px")
    print(f"  border:  {BORDER_MM} mm = {border_px} px")
    print(f"  origin:  ({origin_x_m}, {origin_y_m}) m = 图像左下角对应的世界坐标")
    print(f"  world:   (0,0) = 场地左下, +x → 短边 {FIELD_W_MM/1000}m (水平), +y → 长边 {FIELD_H_MM/1000}m (垂直)")
    print(f"  racks:   画 4 个 ({RACK_SIZE_X_MM}x{RACK_SIZE_Y_MM} mm 实心) — AMCL 锁 LiDAR 用; APPROACH_RACK 走 raw cmd_vel 钻")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--resolution", type=float, default=0.02,
                   help="m/pixel, 默认 0.02 (2cm). 建图越细越费 costmap CPU.")
    p.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "maps"),
                   help="输出目录, 默认 <repo>/maps/")
    args = p.parse_args()
    generate(args.resolution, os.path.abspath(args.out))


if __name__ == "__main__":
    main()
